#!/usr/bin/env bash
# Shared helpers for the sync-agents-* scripts.
#
# None of the three runtimes (Claude Code, Codex, OpenCode) accepts a
# reasoning-effort argument on an ad-hoc subagent dispatch — effort is only
# configurable on a subagent that was defined ahead of time as a file. These
# helpers turn skills/delivering-changes/tiers.json into exactly those files,
# one per (tier, effort) pair, from the templates in ./templates/.

AGENTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$AGENTS_DIR/../.." && pwd)"
TIERS="$REPO/skills/delivering-changes/tiers.json"
TEMPLATES="$AGENTS_DIR/templates"

# Lines equal to this marker are dropped from rendered output, so a template
# can carry an optional line without leaving a blank behind.
DROP_MARKER="@@DROP@@"

preflight() {
  command -v jq &>/dev/null || { echo "ERROR: jq required. Install: brew install jq"; exit 1; }
  [ -f "$TIERS" ] || { echo "ERROR: $TIERS not found"; exit 1; }
}

# render <template> [<key> <value>]...
# Substitutes {{KEY}} placeholders. Uses bash expansion, not sed, so values
# containing / or & need no escaping.
render() {
  local template="$1"; shift
  local out
  out="$(cat "$template")"
  while [ "$#" -gt 0 ]; do
    out="${out//\{\{$1\}\}/$2}"
    shift 2
  done
  printf '%s\n' "$out" | grep -v "^${DROP_MARKER}$"
}

tier_names() { jq -r '.tiers | keys[]' "$TIERS"; }

tier_efforts() { jq -r --arg t "$1" '.tiers[$t].efforts[]' "$TIERS"; }

tier_purpose() { jq -r --arg t "$1" '.tiers[$t].purpose' "$TIERS"; }

# Agent id for a (tier, effort) pair, e.g. standard + low -> delivery-standard-low.
# A 3rd arg suffixes it with a candidate slug (delivery-standard-low--minimax-m3),
# used when a runtime has more than one candidate to choose between.
agent_name() {
  local name="delivery-${1//_/-}-$2"
  [ -n "${3:-}" ] && name="$name--$3"
  echo "$name"
}

agent_description() {
  local tier="$1" effort="$2"
  echo "Pinned to the delivering-changes \"$tier\" tier at $effort effort. $(tier_purpose "$tier")"
}

# First candidate for a runtime, or empty when that runtime has none. Used by
# runtimes where tiers.json only ever lists one candidate (claude, codex).
candidate_field() {
  jq -r --arg t "$1" --arg r "$2" --arg f "$3" \
    '.tiers[$t].candidates[$r][0][$f] // empty' "$TIERS"
}

# Number of candidates for a runtime in a tier (0 if the runtime has none).
candidate_count() {
  jq -r --arg t "$1" --arg r "$2" \
    '.tiers[$t].candidates[$r] // [] | length' "$TIERS"
}

# Field from the Nth (0-based) candidate for a runtime.
candidate_field_at() {
  jq -r --arg t "$1" --arg r "$2" --arg i "$3" --arg f "$4" \
    '.tiers[$t].candidates[$r][($i|tonumber)][$f] // empty' "$TIERS"
}

# Escapes a value for a TOML basic string. Tier purposes are prose and do
# contain double quotes, which would otherwise close the string early.
toml_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

# report_stale <dir> <ext> <generated names...>
# Names the delivery-* agents already in <dir> that this run did not write.
# Renaming the tier/effort scheme otherwise leaves an old agent behind that
# still pins a model but no effort. Reports only — deleting files in the
# operator's home is their call, not the installer's.
report_stale() {
  local dir="$1" ext="$2"; shift 2
  local generated=" $* "
  local stale=()
  local f base
  for f in "$dir"/delivery-*."$ext"; do
    [ -e "$f" ] || continue
    base="$(basename "$f" ".$ext")"
    [[ "$generated" == *" $base "* ]] || stale+=("$base")
  done
  if [ "${#stale[@]}" -gt 0 ]; then
    echo ""
    echo "WARNING: stale agents in $dir not generated by this run:"
    echo "    ${stale[*]}"
    echo "    They predate the current tiers.json naming. Run"
    echo "    scripts/agents/prune-agents.sh to remove them, so a skill"
    echo "    cannot dispatch to an agent with no effort pinned."
  fi
}

# Every agent name the current tiers.json would generate for <runtime>
# (claude, codex, or opencode) — i.e. the "not stale" set. Used by
# prune-agents.sh to decide what's safe to delete without re-running a
# full sync (no HOME writes, no network, works even if that runtime's CLI
# isn't installed).
valid_agent_names() {
  local runtime="$1" tier
  for tier in $(tier_names); do
    local count
    count="$(candidate_count "$tier" "$runtime")"
    [ "$count" -gt 0 ] || continue
    local effort
    for effort in $(tier_efforts "$tier"); do
      if [ "$count" -gt 1 ]; then
        local i model
        for ((i = 0; i < count; i++)); do
          model="$(candidate_field_at "$tier" "$runtime" "$i" model)"
          agent_name "$tier" "$effort" "$model"
        done
      else
        agent_name "$tier" "$effort"
      fi
    done
  done
}
